### ISSUE TITLE
Updated SHA256 for `Around.AppImage`

### ISSUE THREAD

**Issue by jarohen** [sylvainbx/around#5]
Hey @sylvainbx :slightly_smiling_face: I'm now getting `af9d58708bd3e3df9d2ca3c2cf081da27d2a35578bfbc502d780f5d18c336007` for the sha256sum of `Around.AppImage` - have followed your clean-build suggestion from the [AUR page](https://aur.archlinux.org/packages/around#comment-827965)

Cheers,

James

**Comment by sylvainbx** [comment]
Hey James, I can confirm the issue. Seems like around has updated their app. I'll update the package and publish a new version

**Comment by sylvainbx** [comment]
Should be fixed by https://github.com/sylvainbx/around/commit/776bd6530fcef6d77554702942d975706bfff4ba
